#!/bin/bash

dir=~/.config/i3blocks/i3blocklets/yad
yad_type=$1
state=$(cat $dir/yad_state)
pid=$(cat $dir/yad_pid)

echo $state
if [ $state -eq 1 ]; then
	kill $pid
	echo 0 > $dir/yad_state
else
	if [ $yad_type = "update" ]; then
		yad --text-info --filename=<(checkupdates | cut -d " " -f 1; cower -u | cut -d " " -f 2) --no-buttons --width=300 --height=250 --margins=10 --posx=1000 --posy=25 --undecorated &
	elif [ $yad_type = "network" ]; then
		yad --text-info --filename=<($dir/network/network_info) --no-buttons --width=300 --height=100 --margins=10 --posx=1550 --posy=25 --undecorated &
	fi
	
	echo 1 > $dir/yad_state
	echo $! > $dir/yad_pid
fi
