#!/bin/bash

volume=$(awk -F"[][]" '/dB/ { print $2 }' <(amixer sget Master))
vol=$(echo $volume | grep -o -P '[0-9]*(\.[0-9]*)?(?=%)')

#[[ $vol < 34 ]] && [[ $vol > 0 ]] && symbol=" "
#elif [[ $volume < 66 ]]; then
#[[ $vol < 67 ]] && [[ $vol > 33 ]] && symbol=" "
#else 
#[[ $vol < 101 ]] && [[ $vol > 66 ]] && symbol=" "
#fi
symbol=" "
echo "$symbol $volume"
