#!/bin/bash

INTERFACE="wlp2s0"

#------------------------------------------------------------------------

# As per #36 -- It is transparent: e.g. if the machine has no battery or wireless
# connection (think desktop), the corresponding block should not be displayed.
if ! [ -e "/sys/class/net/${INTERFACE}/operstate" ] || ! [ "`cat /sys/class/net/${INTERFACE}/operstate`" = "up" ]
then
    	echo "  Not connected"
#    	echo "#898989"
    	exit 0
fi

SSID_NAME=$(iwgetid -r)
echo "SSID: $SSID_NAME"
# You can put any urgent name so the block will give warning
# if a network with this name is used, like public wifi or alike.
# You can separate multiple values with \|
#URGENT_VALUE=""
#  if [[ "${URGENT_VALUE}" != "" ]] && [[ $(echo "${SSID_NAME}" | grep -we "${URGENT_VALUE}") != "" ]]; then
#    exit 33
#  fi
#fi


